---
apiVersion: v2
name: common
description: Function library for Helm charts
type: library
version: 1.0.1
kubeVersion: ">=1.22.0-0"
keywords:
  - common
  - library
home: https://github.com/fh-gr/common-charts/tree/main/charts/library/common
maintainers:
  - name: Andreas M
    email: andreas.murk@fhgr.ch
