---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: fhgr-common-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://fhgr.github.io/common-charts/
  timeout: 3m
